//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.21 at 01:40:48 PM IDT 
//


package health.logist;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.migdal.health package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.migdal.health
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LogistData }
     * 
     */
    public LogistData createLogistData() {
        return new LogistData();
    }

    /**
     * Create an instance of {@link LogistData.Insured }
     * 
     */
    public LogistData.Insured createLogistDataInsured() {
        return new LogistData.Insured();
    }

    /**
     * Create an instance of {@link LogistData.Insuredpolicy }
     * 
     */
    public LogistData.Insuredpolicy createLogistDataInsuredpolicy() {
        return new LogistData.Insuredpolicy();
    }

    /**
     * Create an instance of {@link LogistData.Claim }
     * 
     */
    public LogistData.Claim createLogistDataClaim() {
        return new LogistData.Claim();
    }

    /**
     * Create an instance of {@link LogistData.Claiminsure }
     * 
     */
    public LogistData.Claiminsure createLogistDataClaiminsure() {
        return new LogistData.Claiminsure();
    }

    /**
     * Create an instance of {@link LogistData.MDEVENT }
     * 
     */
    public LogistData.MDEVENT createLogistDataMDEVENT() {
        return new LogistData.MDEVENT();
    }

    /**
     * Create an instance of {@link LogistData.MDRATEEVENTI }
     * 
     */
    public LogistData.MDRATEEVENTI createLogistDataMDRATEEVENTI() {
        return new LogistData.MDRATEEVENTI();
    }

    /**
     * Create an instance of {@link LogistData.MDCOMPENSATIONPRICELIST }
     * 
     */
    public LogistData.MDCOMPENSATIONPRICELIST createLogistDataMDCOMPENSATIONPRICELIST() {
        return new LogistData.MDCOMPENSATIONPRICELIST();
    }

    /**
     * Create an instance of {@link LogistData.MDVENDORPRICELIST }
     * 
     */
    public LogistData.MDVENDORPRICELIST createLogistDataMDVENDORPRICELIST() {
        return new LogistData.MDVENDORPRICELIST();
    }

    /**
     * Create an instance of {@link LogistData.MDPARAMETERS }
     * 
     */
    public LogistData.MDPARAMETERS createLogistDataMDPARAMETERS() {
        return new LogistData.MDPARAMETERS();
    }

    /**
     * Create an instance of {@link LogistData.MDSERVICELIST }
     * 
     */
    public LogistData.MDSERVICELIST createLogistDataMDSERVICELIST() {
        return new LogistData.MDSERVICELIST();
    }

    /**
     * Create an instance of {@link LogistData.MDSERVICE }
     * 
     */
    public LogistData.MDSERVICE createLogistDataMDSERVICE() {
        return new LogistData.MDSERVICE();
    }

    /**
     * Create an instance of {@link LogistData.MDEVENTSERVICEI }
     * 
     */
    public LogistData.MDEVENTSERVICEI createLogistDataMDEVENTSERVICEI() {
        return new LogistData.MDEVENTSERVICEI();
    }

    /**
     * Create an instance of {@link LogistData.MDFORM }
     * 
     */
    public LogistData.MDFORM createLogistDataMDFORM() {
        return new LogistData.MDFORM();
    }

    /**
     * Create an instance of {@link LogistData.MDTERMSANDEXCEPTIONS }
     * 
     */
    public LogistData.MDTERMSANDEXCEPTIONS createLogistDataMDTERMSANDEXCEPTIONS() {
        return new LogistData.MDTERMSANDEXCEPTIONS();
    }

    /**
     * Create an instance of {@link LogistData.MDRATE }
     * 
     */
    public LogistData.MDRATE createLogistDataMDRATE() {
        return new LogistData.MDRATE();
    }

    /**
     * Create an instance of {@link LogistData.MDFORMRATEI }
     * 
     */
    public LogistData.MDFORMRATEI createLogistDataMDFORMRATEI() {
        return new LogistData.MDFORMRATEI();
    }

    /**
     * Create an instance of {@link LogistData.MDCLAIMDOCUMENTS }
     * 
     */
    public LogistData.MDCLAIMDOCUMENTS createLogistDataMDCLAIMDOCUMENTS() {
        return new LogistData.MDCLAIMDOCUMENTS();
    }

    /**
     * Create an instance of {@link LogistData.MDSERVICEDOCUMENTS }
     * 
     */
    public LogistData.MDSERVICEDOCUMENTS createLogistDataMDSERVICEDOCUMENTS() {
        return new LogistData.MDSERVICEDOCUMENTS();
    }

    /**
     * Create an instance of {@link LogistData.MedicalServiceClaim }
     * 
     */
    public LogistData.MedicalServiceClaim createLogistDataMedicalServiceClaim() {
        return new LogistData.MedicalServiceClaim();
    }

    /**
     * Create an instance of {@link LogistData.Alarm }
     * 
     */
    public LogistData.Alarm createLogistDataAlarm() {
        return new LogistData.Alarm();
    }

    /**
     * Create an instance of {@link LogistData.MDSERVICESERVICELISTI }
     * 
     */
    public LogistData.MDSERVICESERVICELISTI createLogistDataMDSERVICESERVICELISTI() {
        return new LogistData.MDSERVICESERVICELISTI();
    }

    /**
     * Create an instance of {@link LogistData.PolicyExceptionPolicyins }
     * 
     */
    public LogistData.PolicyExceptionPolicyins createLogistDataPolicyExceptionPolicyins() {
        return new LogistData.PolicyExceptionPolicyins();
    }

    /**
     * Create an instance of {@link LogistData.ClaimDocumentinclaim }
     * 
     */
    public LogistData.ClaimDocumentinclaim createLogistDataClaimDocumentinclaim() {
        return new LogistData.ClaimDocumentinclaim();
    }

    /**
     * Create an instance of {@link LogistData.ClaimException }
     * 
     */
    public LogistData.ClaimException createLogistDataClaimException() {
        return new LogistData.ClaimException();
    }

    /**
     * Create an instance of {@link LogistData.ClaimPaymentLine }
     * 
     */
    public LogistData.ClaimPaymentLine createLogistDataClaimPaymentLine() {
        return new LogistData.ClaimPaymentLine();
    }

    /**
     * Create an instance of {@link LogistData.ClaimDocumentclaims }
     * 
     */
    public LogistData.ClaimDocumentclaims createLogistDataClaimDocumentclaims() {
        return new LogistData.ClaimDocumentclaims();
    }

    /**
     * Create an instance of {@link LogistData.Claimlaininclaims }
     * 
     */
    public LogistData.Claimlaininclaims createLogistDataClaimlaininclaims() {
        return new LogistData.Claimlaininclaims();
    }

    /**
     * Create an instance of {@link LogistData.ClaimPaymentLineclaims }
     * 
     */
    public LogistData.ClaimPaymentLineclaims createLogistDataClaimPaymentLineclaims() {
        return new LogistData.ClaimPaymentLineclaims();
    }

    /**
     * Create an instance of {@link LogistData.RateIDPolicy }
     * 
     */
    public LogistData.RateIDPolicy createLogistDataRateIDPolicy() {
        return new LogistData.RateIDPolicy();
    }

    /**
     * Create an instance of {@link LogistData.ComClaim }
     * 
     */
    public LogistData.ComClaim createLogistDataComClaim() {
        return new LogistData.ComClaim();
    }

    /**
     * Create an instance of {@link LogistData.PolicyDetails }
     * 
     */
    public LogistData.PolicyDetails createLogistDataPolicyDetails() {
        return new LogistData.PolicyDetails();
    }

    /**
     * Create an instance of {@link LogistData.TrackingDocClaim }
     * 
     */
    public LogistData.TrackingDocClaim createLogistDataTrackingDocClaim() {
        return new LogistData.TrackingDocClaim();
    }

    /**
     * Create an instance of {@link LogistData.RecDetClaim }
     * 
     */
    public LogistData.RecDetClaim createLogistDataRecDetClaim() {
        return new LogistData.RecDetClaim();
    }

    /**
     * Create an instance of {@link LogistData.RsnStatClaim }
     * 
     */
    public LogistData.RsnStatClaim createLogistDataRsnStatClaim() {
        return new LogistData.RsnStatClaim();
    }

    /**
     * Create an instance of {@link LogistData.Pay }
     * 
     */
    public LogistData.Pay createLogistDataPay() {
        return new LogistData.Pay();
    }

    /**
     * Create an instance of {@link LogistData.ClaiminsureDet }
     * 
     */
    public LogistData.ClaiminsureDet createLogistDataClaiminsureDet() {
        return new LogistData.ClaiminsureDet();
    }

    /**
     * Create an instance of {@link LogistData.PayClaimIns }
     * 
     */
    public LogistData.PayClaimIns createLogistDataPayClaimIns() {
        return new LogistData.PayClaimIns();
    }

    /**
     * Create an instance of {@link LogistData.ClaimLine }
     * 
     */
    public LogistData.ClaimLine createLogistDataClaimLine() {
        return new LogistData.ClaimLine();
    }

}
